/**
 * Generate a Premiere Pro ExtendScript (.jsx) that creates a selects sequence
 * by nesting the existing sacred sequence at specific in/out points.
 *
 * The script references the EXISTING sequence in the project — preserving
 * proxies, captions, color correction, and all other attributes.
 *
 * Usage: File > Scripts > Run Script... in Premiere Pro
 */

/**
 * Convert HH:MM:SS.mmm or M:SS.mmm timecode to seconds.
 */
function tcToSeconds(tc) {
  if (!tc) return 0;
  const parts = tc.replace(',', '.').split(':');
  if (parts.length === 3) {
    return parseInt(parts[0]) * 3600 + parseInt(parts[1]) * 60 + parseFloat(parts[2]);
  } else if (parts.length === 2) {
    return parseInt(parts[0]) * 60 + parseFloat(parts[1]);
  }
  return parseFloat(parts[0]) || 0;
}

/**
 * Build a Premiere Pro ExtendScript (.jsx) for the Sacred Sequencer.
 *
 * @param {Object} opts
 * @param {Array}  opts.soundbites — array of { prefix, start, end, text }
 * @param {string} opts.sacredSequenceName — name of the existing sequence in Premiere
 * @param {string} opts.outputName — name for the new selects sequence
 * @param {number} opts.fps — frame rate (default 23.976)
 * @param {number} opts.gapFrames — gap between clips in frames (default 12)
 * @returns {string} ExtendScript (.jsx) source code
 */
export function buildPremiereScript({ soundbites, sacredSequenceName, outputName, fps = 23.976, gapFrames = 12 }) {
  const gapSec = gapFrames / fps;
  const seqName = outputName || sacredSequenceName + '_Sacred Selects';

  // Pre-compute soundbite data as seconds
  const bites = soundbites.map((b, i) => ({
    inSec: tcToSeconds(b.start),
    outSec: tcToSeconds(b.end),
    name: (b.prefix || 'Soundbite ' + (i + 1)).replace(/'/g, "\\'"),
  }));

  // JSON-encode the soundbite array for embedding in the script
  const bitesJSON = JSON.stringify(bites, null, 2);

  return `/**
 * Sacred Sequencer — Premiere Pro Script
 * Generated by § interpreter
 *
 * This script creates a new sequence "${seqName}"
 * containing nested clips of the existing "${sacredSequenceName}" sequence.
 *
 * Each clip is a NEST of the sacred sequence — changes to the original
 * (captions, color, SRT) will propagate into this selects sequence.
 *
 * Run: File > Scripts > Run Script...
 */

// @target premierepro

(function() {
    // ── Configuration ──
    var SACRED_NAME = '${sacredSequenceName.replace(/'/g, "\\'")}';
    var OUTPUT_NAME = '${seqName.replace(/'/g, "\\'")}';
    var GAP_SECONDS = ${gapSec};
    var TICKS_PER_SECOND = 254016000000;

    var soundbites = ${bitesJSON};

    // ── Helpers ──

    function secToTicks(sec) {
        return String(Math.round(sec * TICKS_PER_SECOND));
    }

    function log(msg) {
        $.writeln('[Sacred Sequencer] ' + msg);
    }

    // ── Find the sacred sequence ──

    log('Looking for sequence: "' + SACRED_NAME + '"...');

    var sacredSeq = null;
    var sacredItem = null;

    for (var i = 0; i < app.project.sequences.numSequences; i++) {
        var seq = app.project.sequences[i];
        if (seq.name === SACRED_NAME) {
            sacredSeq = seq;
            sacredItem = seq.projectItem;
            break;
        }
    }

    if (!sacredSeq || !sacredItem) {
        alert('Sacred Sequencer Error:\\n\\nCould not find sequence "' + SACRED_NAME + '" in this project.\\n\\nMake sure the sequence name matches exactly.');
        return;
    }

    log('Found: "' + sacredSeq.name + '" (duration: ' + sacredSeq.end + ')');

    // ── Create the output sequence ──

    log('Creating sequence: "' + OUTPUT_NAME + '"...');

    // Check if a sequence with this name already exists
    for (var i = 0; i < app.project.sequences.numSequences; i++) {
        if (app.project.sequences[i].name === OUTPUT_NAME) {
            var overwrite = confirm('A sequence named "' + OUTPUT_NAME + '" already exists.\\n\\nReplace it?');
            if (!overwrite) return;
            // We'll create a new one — Premiere allows duplicate names
            break;
        }
    }

    app.project.createNewSequence(OUTPUT_NAME, 'sacred-selects-' + Date.now());
    var newSeq = app.project.activeSequence;

    if (!newSeq || newSeq.name !== OUTPUT_NAME) {
        alert('Sacred Sequencer Error:\\n\\nFailed to create new sequence.');
        return;
    }

    log('Created sequence: "' + newSeq.name + '"');

    // ── Insert soundbites as nested clips ──

    var insertTimeSec = 0;
    var errors = [];

    for (var i = 0; i < soundbites.length; i++) {
        var bite = soundbites[i];
        var durationSec = bite.outSec - bite.inSec;

        if (durationSec <= 0) {
            log('Skipping soundbite ' + (i + 1) + ': zero or negative duration');
            continue;
        }

        log('Inserting ' + (i + 1) + '/' + soundbites.length + ': in=' + bite.inSec.toFixed(3) + 's out=' + bite.outSec.toFixed(3) + 's (' + durationSec.toFixed(2) + 's)');

        try {
            // Set source in/out on the sacred sequence project item
            sacredItem.setInPoint(bite.inSec, 4); // 4 = MediaType.ALL
            sacredItem.setOutPoint(bite.outSec, 4);

            // Insert at current timeline position
            var insertTicks = secToTicks(insertTimeSec);
            newSeq.insertClip(sacredItem, insertTicks, 0, 0);

            insertTimeSec += durationSec + GAP_SECONDS;
        } catch (e) {
            var errMsg = 'Soundbite ' + (i + 1) + ': ' + e.message;
            log('ERROR: ' + errMsg);
            errors.push(errMsg);
        }
    }

    // ── Restore sacred sequence state ──

    try {
        sacredItem.clearInPoint(4);
        sacredItem.clearOutPoint(4);
    } catch (e) {
        log('Note: Could not clear in/out points on sacred sequence (non-critical)');
    }

    // ── Report ──

    var summary = 'Sacred Sequencer Complete!\\n\\n';
    summary += 'Created: "' + OUTPUT_NAME + '"\\n';
    summary += 'Soundbites: ' + soundbites.length + '\\n';
    summary += 'Source: "' + SACRED_NAME + '"\\n';

    if (errors.length > 0) {
        summary += '\\nWarnings (' + errors.length + '):\\n' + errors.join('\\n');
    } else {
        summary += '\\nAll clips inserted successfully.\\n';
        summary += 'Each clip is a NEST of the sacred sequence —\\n';
        summary += 'edits to the original will propagate here.';
    }

    log(summary.replace(/\\\\n/g, '\\n'));
    alert(summary);

})();
`;
}
