/**
 * Fascism Explained Quiz — Question Bank
 * Sourced from Johnny Harris's "Fascism Explained"
 * 25 easy + 25 hard = 50 total questions
 */

const easy = [
  {
    question: 'What does "fascio" mean in Italian?',
    options: ['Iron fist', 'Bundle of sticks', 'National spirit', 'War hammer'],
    answer: 1,
    explanation: 'Fascio means "bundle" in Italian. Mussolini adopted the fasces — a bundle of sticks with an axe — as his symbol, representing unity through strength.',
    timecode: 652,
  },
  {
    question: 'In what city did Mussolini start his fascist movement?',
    options: ['Rome', 'Milan', 'Naples', 'Florence'],
    answer: 1,
    explanation: 'Mussolini founded his fascist movement in the spring of 1919 in Milan, Italy, with a small group of about 100 men.',
    timecode: 593,
  },
  {
    question: 'What was Mussolini\'s political background before fascism?',
    options: ['Military general', 'Socialist newspaper editor', 'Catholic priest', 'Monarchist politician'],
    answer: 1,
    explanation: 'Before becoming a fascist, Mussolini was a rising star in Italian socialism and ran an Italian socialist newspaper.',
    timecode: 430,
  },
  {
    question: 'What were Mussolini\'s violent squads called?',
    options: ['Redshirts', 'Blackshirts', 'Brownshirts', 'Greenshirts'],
    answer: 1,
    explanation: 'Mussolini\'s violent squads, or squadristi, became known as the Blackshirts — a group somewhere between street thugs and a private militia.',
    timecode: 776,
  },
  {
    question: 'How did Italy describe their outcome from World War I?',
    options: ['A glorious triumph', 'A mutilated victory', 'A necessary sacrifice', 'A divine mission'],
    answer: 1,
    explanation: 'Italy was on the winning side of WWI but felt cheated because their allies didn\'t deliver promised territorial gains. They called it a "mutilated victory."',
    timecode: 245,
  },
  {
    question: 'How many soldiers did Germany lose in World War I?',
    options: ['500,000', 'Over two million', 'Five million', 'One million'],
    answer: 1,
    explanation: 'Germany lost over two million soldiers in World War I, plus half a million civilians and 13% of their territory.',
    timecode: 251,
  },
  {
    question: 'What was Mussolini\'s famous slogan as dictator?',
    options: ['Liberty, equality, fraternity', 'Believe, obey, fight', 'Blood and honor', 'One people, one nation'],
    answer: 1,
    explanation: 'As absolute ruler, Mussolini rallied Italy with the slogan "Believe, obey, fight" — demanding total submission to his vision.',
    timecode: 1210,
  },
  {
    question: 'What event did Mussolini lead to pressure Italy\'s king into giving him power?',
    options: ['A general strike', 'The March on Rome', 'A naval blockade', 'An assassination attempt'],
    answer: 1,
    explanation: 'Mussolini directed tens of thousands of Blackshirts to march on Rome. Rather than risk civil war, the king invited Mussolini to become prime minister.',
    timecode: 1075,
  },
  {
    question: 'How many people were in Mussolini\'s movement when it started?',
    options: ['About 100 men', 'About 1,000 men', 'About 10,000 men', 'About 50,000 men'],
    answer: 0,
    explanation: 'Mussolini\'s movement started as a club of about 100 men in Milan. Just 3.5 years later, it was a massive force marching on Rome.',
    timecode: 1083,
  },
  {
    question: 'What did Hitler name his paramilitary group?',
    options: ['The Blackshirts', 'The Brownshirts', 'The Greenshirts', 'The Iron Guard'],
    answer: 1,
    explanation: 'Hitler\'s militia was called the Brownshirts (officially the Sturmabteilung, or stormtroopers), echoing Mussolini\'s Blackshirts.',
    timecode: 1814,
  },
  {
    question: 'What was the full name of the Nazi Party?',
    options: [
      'German Nationalist Party',
      'National Socialist German Workers Party',
      'German People\'s Freedom Party',
      'National Democratic Workers Party',
    ],
    answer: 1,
    explanation: 'Hitler\'s party was the National Socialist German Workers Party — deliberately named to attract workers, even though it opposed actual socialism.',
    timecode: 1840,
  },
  {
    question: 'What building was set on fire that Hitler used to declare a state of emergency?',
    options: ['A church', 'The Reichstag (parliament)', 'A university', 'The presidential palace'],
    answer: 1,
    explanation: 'In February 1933, Germany\'s parliament building (the Reichstag) was set on fire. A communist was found at the scene, giving Hitler the pretext to declare emergency powers.',
    timecode: 2432,
  },
  {
    question: 'In what year did Hitler become chancellor of Germany?',
    options: ['1929', '1931', 'January 1933', '1935'],
    answer: 2,
    explanation: 'Hitler became chancellor in January 1933 after political leaders let him in, thinking they could control him.',
    timecode: 2420,
  },
  {
    question: 'What happened to Germany\'s currency after WWI?',
    options: ['It doubled in value', 'It was replaced by gold', 'It lost 99.9999999% of its value', 'It was banned internationally'],
    answer: 2,
    explanation: 'Post-war debt and reparations destroyed the German mark — it lost 99.9999999% of its value, leading to wheelbarrows of cash for basic goods.',
    timecode: 288,
  },
  {
    question: 'Who did Hitler blame most for Germany\'s problems in Mein Kampf?',
    options: ['The French', 'Communists and Jews', 'The British', 'The Italian fascists'],
    answer: 1,
    explanation: 'In Mein Kampf, Hitler blamed communists and Jews for Germany\'s decline, claiming Jews were using communism to undermine the German nation.',
    timecode: 2100,
  },
  {
    question: 'What year was Kristallnacht?',
    options: ['1933', '1935', '1938', '1941'],
    answer: 2,
    explanation: 'In 1938, the Nazis unleashed Kristallnacht — destroying hundreds of synagogues, smashing thousands of Jewish shops, and arresting 30,000 Jewish men.',
    timecode: 2610,
  },
  {
    question: 'How many Jewish people were killed in the Holocaust?',
    options: ['One million', 'Three million', 'About six million', 'Ten million'],
    answer: 2,
    explanation: 'Hitler\'s regime systematically murdered about six million Jews, along with millions of Poles, Slavs, Roma, and other civilians.',
    timecode: 2670,
  },
  {
    question: 'What political ideology were the fascists most opposed to?',
    options: ['Monarchy', 'Communism and socialism', 'Capitalism', 'Anarchism'],
    answer: 1,
    explanation: 'Crushing socialists and communists was one of the key aspects of fascism. Mussolini\'s Blackshirts targeted socialist meetings, newspapers, and leaders.',
    timecode: 748,
  },
  {
    question: 'What concept did Mussolini call "trenchocracy"?',
    options: ['Government by military generals', 'Rule by war veterans purified through combat', 'A system of underground bunkers', 'Democracy in wartime'],
    answer: 1,
    explanation: 'Mussolini believed war veterans had been purified by violence and sacrifice, creating a new elite — a "trenchocracy," the aristocracy of the trenches.',
    timecode: 568,
  },
  {
    question: 'What failed event led to Hitler being imprisoned?',
    options: ['An assassination attempt on the president', 'The Beer Hall Putsch', 'A bombing campaign', 'A military mutiny'],
    answer: 1,
    explanation: 'In 1923, Hitler and 600 Brownshirts tried to seize power starting from a Munich beer hall. The coup failed completely and Hitler was arrested and jailed.',
    timecode: 1990,
  },
  {
    question: 'What book did Hitler write while in prison?',
    options: ['The Prince', 'Das Kapital', 'Mein Kampf', 'The Will to Power'],
    answer: 2,
    explanation: 'While in prison after the failed Beer Hall Putsch, Hitler wrote Mein Kampf — part autobiography, part racial manifesto, part political blueprint.',
    timecode: 2070,
  },
  {
    question: 'Why did Mussolini break with the socialists?',
    options: ['He wanted to become king', 'He supported Italy joining WWI and they were anti-war', 'They expelled him for corruption', 'He converted to communism'],
    answer: 1,
    explanation: 'Mussolini broke with the socialists because he believed Italy should join WWI, while the socialists were firmly anti-war. They kicked him out of the party.',
    timecode: 444,
  },
  {
    question: 'What percentage of territory did Germany lose after WWI?',
    options: ['5%', '13%', '25%', '40%'],
    answer: 1,
    explanation: 'Germany lost 13% of its territory after WWI, which contained 10% of its population, on top of massive military casualties and crippling debt.',
    timecode: 257,
  },
  {
    question: 'How much did Germany have to pay in reparations (in today\'s money)?',
    options: ['$50 billion', 'Half a trillion dollars', '$5 trillion', '$100 billion'],
    answer: 1,
    explanation: 'The peace deal required Germany to pay the victors about half a trillion dollars in today\'s money — a debt they only recently finished paying off.',
    timecode: 269,
  },
  {
    question: 'What did Hitler do to the Constitution after the Reichstag fire?',
    options: ['He amended it slightly', 'He suspended it within days', 'He held a referendum', 'He replaced it with Mein Kampf'],
    answer: 1,
    explanation: 'Using the Reichstag fire as a pretext for emergency powers, Hitler suspended the Constitution within days — ending freedom of expression, press, and protections from searches.',
    timecode: 2453,
  },
];

const hard = [
  {
    question: 'What ancient Roman symbol did Mussolini adopt for his movement?',
    options: ['An eagle clutching a laurel', 'The fasces — a bundle of sticks with an axe', 'A she-wolf suckling twins', 'A gladius sword and shield'],
    answer: 1,
    explanation: 'The fasces — a bundle of sticks bound around an axe — was an ancient Roman symbol of authority. Mussolini adopted it to represent unity and punishment under his rule.',
    timecode: 633,
  },
  {
    question: 'Where did the term "Aryan" actually originate from, according to the video?',
    options: ['Ancient Greek philosophy', 'Indo-Iranian linguistics', 'Norse mythology', 'Egyptian hieroglyphics'],
    answer: 1,
    explanation: 'The word "Aryan" came from the Indo-Iranian people and was a linguistic classification. German nationalists misappropriated it to fabricate a myth of racial superiority.',
    timecode: 1640,
  },
  {
    question: 'What was the "Dolchstoß" myth?',
    options: [
      'The belief that Germany\'s army was invincible',
      'The claim that Germany was stabbed in the back by betrayers at home',
      'A conspiracy about stolen weapons',
      'A theory about secret Allied spies',
    ],
    answer: 1,
    explanation: 'The "Dolchstoß" (stab-in-the-back myth) claimed Germany didn\'t truly lose WWI militarily but was betrayed by weak politicians, communists, and Jews on the home front.',
    timecode: 1740,
  },
  {
    question: 'What concept from Hitler\'s ideology linked racial purity to territorial expansion?',
    options: ['Master plan', 'Blood and soil', 'Iron will', 'Sacred destiny'],
    answer: 1,
    explanation: 'Hitler\'s "blood and soil" ideology tied the purification of the German race to the reclaiming of sacred homeland — justifying both racial persecution and territorial conquest.',
    timecode: 2163,
  },
  {
    question: 'Why did Italian business elites initially support Mussolini\'s Blackshirts?',
    options: [
      'They wanted to expand Italian colonies',
      'They feared communist worker revolutions would seize their wealth',
      'Mussolini promised them government contracts',
      'The king ordered them to',
    ],
    answer: 1,
    explanation: 'Italian business elites funded the Blackshirts because they feared communists would seize their wealth and land. The Blackshirts were even hired to break up worker strikes.',
    timecode: 906,
  },
  {
    question: 'How long did it take Mussolini to go from founding his movement to marching on Rome?',
    options: ['About 6 months', 'About 3.5 years', 'About 10 years', 'About 1 year'],
    answer: 1,
    explanation: 'Mussolini\'s movement started as a club of about 100 men in Milan in spring 1919. Just 3.5 years later, in October 1922, he led the March on Rome.',
    timecode: 1083,
  },
  {
    question: 'Why did the naming of Hitler\'s party as "National Socialist" matter?',
    options: [
      'It reflected genuine socialist beliefs',
      'It was a branding play to attract workers who supported socialist movements',
      'It was required by German law',
      'It honored the Russian Revolution',
    ],
    answer: 1,
    explanation: 'The name was deliberately chosen to attract workers interested in socialist movements, even though the Nazis opposed actual socialism. It was purely a branding play.',
    timecode: 1845,
  },
  {
    question: 'What lesson did Hitler learn from his failed Beer Hall Putsch?',
    options: [
      'He needed a bigger army',
      'He needed to gain mainstream political acceptance before seizing power',
      'Violence never works',
      'He should ally with the communists',
    ],
    answer: 1,
    explanation: 'Hitler realized he couldn\'t jump straight to power through violence alone. He needed to gain acceptance from business elites and work through the democratic system first — then destroy it from within.',
    timecode: 2160,
  },
  {
    question: 'What economic event in 1929 dramatically boosted Nazi support in Germany?',
    options: ['A trade embargo', 'The global financial crash and Great Depression', 'The discovery of oil', 'A new gold standard'],
    answer: 1,
    explanation: 'The 1929 financial crash devastated Germany\'s already-fragile economy. Soon one in three Germans were out of work, making Hitler\'s message of scapegoating and national rebirth far more appealing.',
    timecode: 2280,
  },
  {
    question: 'What fraction of Germans were unemployed after the 1929 crash?',
    options: ['One in five', 'One in three', 'One in ten', 'One in two'],
    answer: 1,
    explanation: 'After the 1929 crash, one in three Germans were out of work. This mass suffering made the population far more receptive to Hitler\'s extremist message.',
    timecode: 2301,
  },
  {
    question: 'How did Hitler get the Reichstag fire to serve his purposes?',
    options: [
      'He blamed his own party to gain sympathy',
      'He used a communist found at the scene to declare emergency and suspend the Constitution',
      'He blamed a foreign government and declared war',
      'He used it to justify new elections',
    ],
    answer: 1,
    explanation: 'A communist was found at the scene of the Reichstag fire. Hitler used this to declare a state of emergency and suspended the entire Constitution within days.',
    timecode: 2432,
  },
  {
    question: 'What rights were suspended in Germany after the Reichstag fire?',
    options: [
      'Only the right to vote',
      'Freedom of expression, press, and protections from search and seizure',
      'Only freedom of assembly',
      'Only military service exemptions',
    ],
    answer: 1,
    explanation: 'The emergency decree suspended freedom of expression, freedom of the press, and protections from search and seizure — the entire liberal democratic legal framework.',
    timecode: 2459,
  },
  {
    question: 'By what year had Mussolini fully dismantled Italian democracy?',
    options: ['1922', '1925', '1930', '1935'],
    answer: 1,
    explanation: 'By 1925, Mussolini had abolished elections, banned other political parties, censored the press, and created a secret police — completing his dismantling of Italian democracy.',
    timecode: 1199,
  },
  {
    question: 'What role did the Italian king play in Mussolini\'s rise?',
    options: [
      'He fought Mussolini militarily',
      'He invited Mussolini to become prime minister rather than risk civil war',
      'He abdicated immediately',
      'He allied with the communists against Mussolini',
    ],
    answer: 1,
    explanation: 'When Mussolini\'s Blackshirts gathered outside Rome, the king — knowing many in his own army sympathized with the fascists — chose to invite Mussolini to become PM rather than fight.',
    timecode: 1100,
  },
  {
    question: 'How many Blackshirts did Mussolini\'s movement eventually grow to?',
    options: ['10,000', '50,000', 'A quarter million', 'One million'],
    answer: 2,
    explanation: 'Mussolini\'s Blackshirts swelled from about 100 men in 1919 to a quarter million (250,000) people, becoming a force that the Italian state could not easily suppress.',
    timecode: 783,
  },
  {
    question: 'Why did Hitler decide to pursue power through elections instead of another coup?',
    options: [
      'He became genuinely democratic',
      'He realized he must use democracy to gain power and then destroy it from within',
      'The army forced him to',
      'Mussolini told him to stop',
    ],
    answer: 1,
    explanation: 'After the failed Beer Hall Putsch, Hitler wrote in Mein Kampf that he needed "determined cooperation between brute force and political aims wisely chosen" — using democracy to destroy it.',
    timecode: 2205,
  },
  {
    question: 'What was the result when the Nazi Party first ran in elections in 1928?',
    options: ['They won a majority', 'They got the second most votes', 'They barely got any votes', 'They won a coalition'],
    answer: 2,
    explanation: 'In the 1928 election, the Nazis barely got any votes. But Hitler was undeterred and kept spreading his message of racial superiority and scapegoating.',
    timecode: 2246,
  },
  {
    question: 'In what year did Kristallnacht occur, and how many Jewish men were arrested?',
    options: ['1935; 10,000', '1938; 30,000', '1940; 50,000', '1936; 20,000'],
    answer: 1,
    explanation: 'Kristallnacht happened in 1938. Hundreds of synagogues were destroyed, thousands of Jewish shops smashed, and 30,000 Jewish men were arrested and sent to camps.',
    timecode: 2610,
  },
  {
    question: 'What year did Hitler strip German Jews of citizenship?',
    options: ['1933', '1935', '1938', '1940'],
    answer: 1,
    explanation: 'In 1935, the Nuremberg Laws stripped any German Jew of citizenship and their rights — years before the mass violence of Kristallnacht and the Holocaust.',
    timecode: 2580,
  },
  {
    question: 'Why did both Italian and German political establishments initially allow fascists into power?',
    options: [
      'They were forced at gunpoint',
      'They thought they could control the fascists while using them against communists',
      'They genuinely agreed with fascist ideology',
      'International treaties required it',
    ],
    answer: 1,
    explanation: 'In both countries, mainstream politicians and business elites thought they could "tame" the fascists and use them as a weapon against communism, while keeping their extreme ideas in check.',
    timecode: 2390,
  },
  {
    question: 'What was the Sturmabteilung?',
    options: [
      'Hitler\'s personal bodyguard',
      'The official name of the Brownshirts (stormtroopers)',
      'Germany\'s regular army',
      'A secret intelligence agency',
    ],
    answer: 1,
    explanation: 'The Sturmabteilung (stormtroopers) was the official name for Hitler\'s Brownshirts — his paramilitary force named after the German Army\'s elite WWI assault unit.',
    timecode: 1821,
  },
  {
    question: 'How did German nationalists misuse the field of linguistics to create the Aryan myth?',
    options: [
      'They invented a new language',
      'They took a linguistic term for a language family and reimagined it as an actual superior race',
      'They decoded ancient Roman texts',
      'They discovered a new alphabet',
    ],
    answer: 1,
    explanation: 'Linguists found many world languages share a common ancestor they called "Aryan." German nationalists twisted this into the myth of an actual Aryan master race originating in Germany.',
    timecode: 1656,
  },
  {
    question: 'What symbol did German nationalists adopt as a supposed "ancient Aryan rune"?',
    options: ['An iron cross', 'A hooked cross (swastika)', 'A double-headed eagle', 'A runic shield'],
    answer: 1,
    explanation: 'German nationalists adopted the hooked cross — a symbol found across many cultures — and rebranded it as an ancient Aryan rune connecting Germany to a mythical master race.',
    timecode: 1690,
  },
  {
    question: 'What imagined past did Mussolini promise to restore for Italy?',
    options: ['The Venetian Republic', 'The glory of the Roman Empire', 'The Italian Renaissance', 'The Byzantine Empire'],
    answer: 1,
    explanation: 'Mussolini demanded belief in his story that Italy would be made "great, respected, and feared" again — restoring the glory of an imagined Roman Empire past.',
    timecode: 1227,
  },
  {
    question: 'What did the fascists accuse Jewish people of doing, according to the video?',
    options: [
      'Being too wealthy',
      'Projecting onto Jews everything the fascists themselves were doing',
      'Refusing to serve in the military',
      'Allying with Italy against Germany',
    ],
    answer: 1,
    explanation: 'The Nazis assigned to Jews everything they themselves were doing — conspiracy, propaganda, desire for world domination — claiming they were merely "responding" to what Jews had already done.',
    timecode: 2560,
  },
];

export { easy, hard };
