/**
 * Flying Money Quiz — Question Bank
 * Sourced from Johnny Harris's "How Criminals Move Trillions Without a Trace"
 * 25 easy + 25 hard = 50 total questions
 */

const easy = [
  {
    question: 'What dynasty invented flying money?',
    options: ['Song Dynasty', 'Tang Dynasty', 'Ming Dynasty', 'Han Dynasty'],
    answer: 1,
    explanation: 'Merchants in the Tang Dynasty created a system of paper receipts to avoid carrying heavy copper coins — the origin of "flying money."',
    timecode: 329,
  },
  {
    question: 'Flying money is thought to be the first form of what?',
    options: ['Banking', 'Paper money', 'Cryptocurrency', 'Wire transfers'],
    answer: 1,
    explanation: 'These paper receipts were essentially IOUs that could be redeemed for coins — making them the first known form of paper money.',
    timecode: 416,
  },
  {
    question: 'What is the foundation that makes flying money work?',
    options: ['Technology', 'Trust', 'Government backing', 'Gold reserves'],
    answer: 1,
    explanation: 'The entire system runs on trust between brokers. No contracts, no receipts — just mutual faith that debts will be settled.',
    timecode: 403,
  },
  {
    question: 'How much in illicit proceeds flows through criminal systems annually?',
    options: ['$500 billion', '$1 trillion', '$4 trillion', '$10 trillion'],
    answer: 2,
    explanation: 'An estimated $4 trillion in illicit proceeds flows through shadow financial systems every year.',
    timecode: 116,
  },
  {
    question: 'What annual limit did China set on moving money out of the country?',
    options: ['$10,000 USD', '$25,000 USD', '$50,000 USD', '$100,000 USD'],
    answer: 2,
    explanation: 'China caps outbound transfers at $50,000 per person per year, driving demand for underground money-moving systems.',
    timecode: 553,
  },
  {
    question: 'What is hawala described as in Afghanistan?',
    options: ['An illegal network', 'The de facto banking system', 'A terrorist funding tool', 'A government program'],
    answer: 1,
    explanation: 'In Afghanistan, hawala isn\'t underground at all — it\'s the de facto banking system that most of the country relies on.',
    timecode: 852,
  },
  {
    question: 'What is called "the cocaine of the sea"?',
    options: ['Shark fin', 'Totoaba swim bladder', 'Sea cucumber', 'Abalone'],
    answer: 1,
    explanation: 'Totoaba swim bladders are so valuable on the black market that they\'ve earned the nickname "the cocaine of the sea."',
    timecode: 1330,
  },
  {
    question: 'Which cartel expanded into illegal fishing in Mexico?',
    options: ['Jalisco New Generation', 'Sinaloa Cartel', 'Gulf Cartel', 'Los Zetas'],
    answer: 1,
    explanation: 'The Sinaloa Cartel expanded into poaching totoaba fish because the profits rivaled drug trafficking.',
    timecode: 1304,
  },
  {
    question: 'What two technologies could make flying money "almost unbreakable"?',
    options: [
      'AI and blockchain',
      'Encryption and decentralized currency',
      'VPNs and the dark web',
      'Quantum computing and satellites',
    ],
    answer: 1,
    explanation: 'Encryption and decentralized currencies like crypto could make these shadow networks nearly impossible for law enforcement to crack.',
    timecode: 1815,
  },
  {
    question: 'What form of currency were people carrying in Tang Dynasty China?',
    options: ['Silver bars', 'Copper coins', 'Gold nuggets', 'Silk bolts'],
    answer: 1,
    explanation: 'People carried heavy strings of copper coins, which made long-distance trade dangerous and impractical — sparking the invention of flying money.',
    timecode: 339,
  },
  {
    question: 'Why was carrying copper coins a problem for Tang Dynasty merchants?',
    options: ['They were counterfeited easily', 'They were too heavy and attracted bandits', 'They corroded quickly', 'Banks refused them'],
    answer: 1,
    explanation: 'Copper coins were extremely heavy to carry in large quantities and made merchants targets for robbery along trade routes.',
    timecode: 339,
  },
  {
    question: 'What country ships fentanyl precursor chemicals to Mexican cartels?',
    options: ['India', 'China', 'Russia', 'North Korea'],
    answer: 1,
    explanation: 'Fentanyl precursor chemicals are manufactured in China and shipped to Mexican cartels as part of the global flying money cycle.',
    timecode: 1423,
  },
  {
    question: 'How many elephants were killed per year for ivory at the peak?',
    options: ['5,000 to 10,000', '15,000 to 20,000', '40,000 to 50,000', '100,000+'],
    answer: 2,
    explanation: 'At the peak, 40,000 to 50,000 elephants were being slaughtered every year to feed the illegal ivory trade.',
    timecode: 971,
  },
  {
    question: 'What does a flying money system leave behind for law enforcement to trace?',
    options: ['Bank records', 'Digital receipts', 'Nothing — no paper trail', 'Tax filings'],
    answer: 2,
    explanation: 'Because flying money relies on trust and informal ledgers, it produces no paper trail for authorities to follow.',
    timecode: 403,
  },
  {
    question: 'What kind of organization did Andrea Crosta create?',
    options: ['A wildlife sanctuary', 'An intelligence agency for Earth', 'An international police force', 'A blockchain tracking system'],
    answer: 1,
    explanation: 'Andrea Crosta created what he calls "the first intelligence agency for Earth" — dedicated to investigating environmental crime networks.',
    timecode: 987,
  },
  {
    question: 'What percentage of world GDP is estimated to be proceeds of crime?',
    options: ['Less than 1%', '1 to 2%', '3 to 5%', '8 to 10%'],
    answer: 2,
    explanation: 'The UN estimates that 3 to 5% of global GDP — trillions of dollars — comes from criminal activity.',
    timecode: 109,
  },
  {
    question: 'In what body of water did cartels poach the endangered totoaba fish?',
    options: ['Gulf of Mexico', 'Sea of Cortez', 'Caribbean Sea', 'Pacific Ocean'],
    answer: 1,
    explanation: 'The Sinaloa Cartel poaches totoaba in the Sea of Cortez in northern Mexico, driving the species toward extinction.',
    timecode: 1304,
  },
  {
    question: 'What makes hawala different from a regular bank transfer?',
    options: ['It\'s faster', 'It uses no formal banking channels', 'It\'s government-regulated', 'It requires photo ID'],
    answer: 1,
    explanation: 'Hawala operates entirely outside the formal banking system — money moves through a network of trusted brokers with no institutional oversight.',
    timecode: 852,
  },
  {
    question: 'What problem in China created massive demand for underground money networks?',
    options: ['Bank collapses', 'Strict capital controls', 'Currency devaluation', 'Internet censorship'],
    answer: 1,
    explanation: 'China\'s strict capital controls — capping outbound transfers at $50,000/year — pushed people toward underground systems to move money abroad.',
    timecode: 553,
  },
  {
    question: 'What type of crime does Andrea Crosta\'s organization investigate?',
    options: ['Cybercrime', 'Environmental crime', 'Financial fraud', 'Human trafficking'],
    answer: 1,
    explanation: 'Crosta\'s organization focuses on environmental crime — from ivory poaching to illegal fishing — and the money networks behind them.',
    timecode: 987,
  },
  {
    question: 'How do hawala brokers typically settle debts between each other?',
    options: ['Bank wire transfers', 'Through trade and goods', 'Cash deliveries by courier', 'Cryptocurrency'],
    answer: 1,
    explanation: 'Rather than sending cash, hawala brokers settle their debts through trade — manipulating the prices of goods shipped between countries.',
    timecode: 793,
  },
  {
    question: 'What does flying money allow people to move across borders?',
    options: ['Physical cash', 'Value — without moving actual money', 'Gold bars', 'Counterfeit bills'],
    answer: 1,
    explanation: 'Flying money moves value, not physical currency. Brokers on each side of a border pay out locally, so money never actually crosses.',
    timecode: 403,
  },
  {
    question: 'How much drug cash vanished from the streets of a single US city?',
    options: ['More than $5 million', 'More than $50 million', 'More than $500 million', 'More than $1 billion'],
    answer: 1,
    explanation: 'Law enforcement noticed more than $50 million in drug cash simply vanished from one US city — moved out through flying money networks.',
    timecode: 88,
  },
  {
    question: 'What is the name of the fentanyl precursor chemical mentioned in the video?',
    options: ['Methylamine', 'Phenylethyl bromide', 'Acetic anhydride', 'Pseudoephedrine'],
    answer: 1,
    explanation: 'Phenylethyl bromide, a key chemical for manufacturing fentanyl, is shipped from China to cartels as part of the flying money settlement cycle.',
    timecode: 1423,
  },
  {
    question: 'Why did the Sinaloa Cartel get into wildlife trafficking?',
    options: ['To fund weapons purchases', 'The profits rival drug trafficking', 'To launder drug money', 'Government crackdowns on drugs'],
    answer: 1,
    explanation: 'Totoaba swim bladders are so valuable that the profits rival traditional drug trafficking, making wildlife crime an attractive side business for cartels.',
    timecode: 1304,
  },
];

const hard = [
  {
    question: 'What trade manipulation technique do flying money brokers use to move value across borders?',
    options: ['Counterfeiting currency', 'Over- or under-invoicing goods', 'Stock market manipulation', 'Real estate flipping'],
    answer: 1,
    explanation: 'Brokers manipulate the invoiced price of legitimate goods — over- or under-invoicing — so the price difference settles debts without moving cash.',
    timecode: 793,
  },
  {
    question: 'Totoaba swim bladders sell for what price range?',
    options: [
      'Hundreds of dollars per kilogram',
      'A few thousand dollars per kilogram',
      'Tens of thousands of dollars per kilogram',
      'Over a million dollars per kilogram',
    ],
    answer: 2,
    explanation: 'Totoaba swim bladders fetch tens of thousands of dollars per kilogram on the black market, making them more valuable by weight than many drugs.',
    timecode: 1346,
  },
  {
    question: 'Why is trade-based money laundering particularly hard to detect?',
    options: [
      'It happens at night',
      'The goods actually ship — only the prices are manipulated',
      'It uses fake companies',
      'It only happens offshore',
    ],
    answer: 1,
    explanation: 'The trade is real, the goods are real, the shipping is real — the only thing manipulated is the price on the invoice, making it nearly invisible to regulators.',
    timecode: 793,
  },
  {
    question: 'What was happening to drug cash that puzzled US law enforcement?',
    options: [
      'It was being counterfeited',
      'Massive amounts vanished without crossing borders physically',
      'It was being destroyed',
      'Banks were secretly hiding it',
    ],
    answer: 1,
    explanation: 'Tens of millions in cash vanished from city streets with no trace — no bulk cash smuggling detected at borders, because flying money moved the value, not the bills.',
    timecode: 88,
  },
  {
    question: 'Why is Afghanistan\'s use of hawala different from how it\'s used elsewhere?',
    options: [
      'It\'s government-run there',
      'It\'s the primary financial system, not an underground one',
      'It uses cryptocurrency',
      'It\'s connected to banks',
    ],
    answer: 1,
    explanation: 'In most countries hawala operates in the shadows, but in Afghanistan it IS the banking system — the main way most people send and receive money.',
    timecode: 852,
  },
  {
    question: 'What role does legitimate international trade play in flying money?',
    options: [
      'None — it\'s completely separate',
      'It provides cover for moving value through invoice manipulation',
      'It competes with flying money',
      'Governments use it to track flying money',
    ],
    answer: 1,
    explanation: 'Legitimate trade is the perfect cover — real goods move between real companies, but manipulated invoices secretly transfer value for criminal networks.',
    timecode: 793,
  },
  {
    question: 'Why might cryptocurrency make flying money networks even harder to stop?',
    options: [
      'Crypto is legal everywhere',
      'It adds encryption and removes the need for physical settlement',
      'Governments can\'t regulate any crypto',
      'Crypto is completely anonymous',
    ],
    answer: 1,
    explanation: 'Cryptocurrency adds a layer of encryption and eliminates the need for physical goods or cash to settle debts between brokers.',
    timecode: 1815,
  },
  {
    question: 'What links ivory poaching, totoaba fishing, and drug trafficking according to the video?',
    options: [
      'They use the same smuggling routes',
      'They all rely on flying money networks to move profits',
      'They\'re run by the same people',
      'They all happen in Mexico',
    ],
    answer: 1,
    explanation: 'All three criminal enterprises plug into the same flying money networks to move their profits across borders invisibly.',
    timecode: 1304,
  },
  {
    question: 'What specific chemical is shipped from China to Mexico as part of the flying money cycle?',
    options: ['Methylamine', 'Phenylethyl bromide', 'Ephedrine', 'Potassium permanganate'],
    answer: 1,
    explanation: 'Phenylethyl bromide — a fentanyl precursor — flows from China to Mexican cartels, with the debt settled through flying money rather than direct payment.',
    timecode: 1423,
  },
  {
    question: 'How does value move in a hawala network without physical cash crossing borders?',
    options: [
      'Through bank wires under fake names',
      'Brokers on each side pay out locally and settle debts later',
      'Digital transfers through shell companies',
      'Government subsidies cover the gap',
    ],
    answer: 1,
    explanation: 'A broker in one country pays out from their own funds, while a broker in another country collects. They settle the difference later through trade or other means.',
    timecode: 852,
  },
  {
    question: 'What challenge does decentralization pose for law enforcement fighting flying money?',
    options: [
      'There\'s no central system or server to shut down',
      'It requires too many agents',
      'The technology is too advanced',
      'It\'s protected by international law',
    ],
    answer: 0,
    explanation: 'Unlike a bank you can freeze or a server you can seize, flying money is a distributed network of individual brokers — there\'s no central node to target.',
    timecode: 1815,
  },
  {
    question: 'What is the connection between China\'s capital controls and global criminal finance?',
    options: [
      'China funds criminal groups directly',
      'The $50K limit creates demand for underground services that criminals also use',
      'Chinese banks launder money intentionally',
      'There is no connection',
    ],
    answer: 1,
    explanation: 'China\'s $50K annual cap on moving money out creates a huge market for underground money brokers — and those same brokers serve criminal clients too.',
    timecode: 553,
  },
  {
    question: 'Why has flying money survived for over a thousand years?',
    options: [
      'Government support',
      'It solves a real need that formal banking systems don\'t',
      'Technological advances',
      'Criminal demand alone sustains it',
    ],
    answer: 1,
    explanation: 'Flying money endures because it meets genuine needs — fast, cheap, borderless transfers — that formal banking systems are too slow, expensive, or inaccessible to provide.',
    timecode: 416,
  },
  {
    question: 'Why is the totoaba fish so critically endangered?',
    options: [
      'Climate change destroyed its habitat',
      'Overfishing for its swim bladder drove it toward extinction',
      'Oil spills in the Sea of Cortez',
      'Invasive species competition',
    ],
    answer: 1,
    explanation: 'The totoaba is hunted almost exclusively for its swim bladder, which commands black market prices rivaling illegal drugs.',
    timecode: 1330,
  },
  {
    question: 'What makes the ivory and totoaba trades similar in how they move money?',
    options: [
      'Both use cryptocurrency',
      'Both funnel profits through the same type of informal broker networks',
      'Both are run by the same cartel',
      'Both use offshore bank accounts',
    ],
    answer: 1,
    explanation: 'Both the ivory and totoaba trades rely on the same kind of trust-based broker networks to move their profits — the modern descendants of flying money.',
    timecode: 1330,
  },
  {
    question: 'How does flying money make environmental crime more dangerous?',
    options: [
      'It provides weapons to poachers',
      'It lets criminal profits vanish across borders, making enforcement nearly impossible',
      'It funds habitat destruction directly',
      'It bribes park rangers',
    ],
    answer: 1,
    explanation: 'Flying money lets poaching and trafficking profits disappear into a borderless network, so even if you catch a poacher, the financial network behind them is invisible.',
    timecode: 987,
  },
  {
    question: 'What happens in a hawala transaction when a broker\'s debts grow too large?',
    options: [
      'They declare bankruptcy',
      'They settle through trade — shipping goods whose invoices absorb the imbalance',
      'They borrow from banks',
      'The network collapses',
    ],
    answer: 1,
    explanation: 'When debts between brokers grow, they\'re settled through legitimate trade — goods are shipped and invoiced at manipulated prices to balance the books.',
    timecode: 793,
  },
  {
    question: 'Why did law enforcement struggle to explain where drug cash was going?',
    options: [
      'The cash was being burned',
      'Billions in drug profits produced almost no bulk cash seizures at borders',
      'Banks were cooperating with criminals',
      'The DEA lacked funding',
    ],
    answer: 1,
    explanation: 'The math didn\'t add up — huge drug profits on the streets but almost no corresponding bulk cash caught leaving the country, because flying money moved value without moving bills.',
    timecode: 88,
  },
  {
    question: 'What makes flying money fundamentally different from traditional money laundering?',
    options: [
      'It uses digital currency',
      'Value moves across borders while the actual money stays put',
      'It requires corrupt banks',
      'It only works in developing countries',
    ],
    answer: 1,
    explanation: 'In traditional laundering, dirty cash moves through banks. In flying money, the cash never crosses a border — only the value does, through a chain of trusted brokers.',
    timecode: 403,
  },
  {
    question: 'What economic force drives ordinary Chinese citizens to use underground money services?',
    options: [
      'Hyperinflation',
      'The desire to buy property or invest abroad beyond the $50K annual cap',
      'Distrust of the yuan',
      'High banking fees',
    ],
    answer: 1,
    explanation: 'Many Chinese citizens want to buy overseas property or send children to foreign universities — costs that far exceed the $50,000 annual transfer limit.',
    timecode: 553,
  },
  {
    question: 'How does the scale of global criminal proceeds compare to national economies?',
    options: [
      'It\'s smaller than most countries\' GDP',
      'At 3-5% of world GDP, it rivals the output of major nations',
      'It\'s about 0.1% of world GDP',
      'It only affects developing countries',
    ],
    answer: 1,
    explanation: 'At 3-5% of world GDP — roughly $4 trillion — global criminal proceeds would rank as one of the largest economies in the world if it were a country.',
    timecode: 109,
  },
  {
    question: 'Why is the Tang Dynasty\'s invention of flying money considered revolutionary?',
    options: [
      'It replaced gold as currency',
      'It separated the concept of value from physical currency for the first time',
      'It created the first banks',
      'It standardized coin weights',
    ],
    answer: 1,
    explanation: 'Flying money\'s breakthrough was the idea that value could be represented on paper and redeemed elsewhere — separating money from its physical form.',
    timecode: 416,
  },
  {
    question: 'What do fentanyl precursors, totoaba bladders, and ivory all have in common?',
    options: [
      'They\'re all manufactured in China',
      'They\'re all high-value goods that settle debts in flying money networks',
      'They\'re all legal in some countries',
      'They all travel the same shipping route',
    ],
    answer: 1,
    explanation: 'All three are high-value commodities used within flying money networks — physical goods that move between countries to balance the books between brokers.',
    timecode: 1423,
  },
  {
    question: 'What fundamental problem did flying money originally solve in the Tang Dynasty?',
    options: [
      'Inflation made coins worthless',
      'Long-distance trade was impractical with heavy coins and dangerous roads',
      'The emperor banned gold',
      'There weren\'t enough coins in circulation',
    ],
    answer: 1,
    explanation: 'Merchants faced two problems: copper coins were extremely heavy to transport in bulk, and carrying visible wealth made them targets for bandits on trade routes.',
    timecode: 339,
  },
  {
    question: 'Why does the video suggest flying money may never be fully stopped?',
    options: [
      'Governments secretly support it',
      'It serves both legitimate needs and criminal ones, and encryption will make it invisible',
      'There aren\'t enough police',
      'It\'s protected by free speech laws',
    ],
    answer: 1,
    explanation: 'Flying money has survived 1,000+ years because it fills real gaps in global finance. With encryption and crypto removing the last physical traces, the video suggests it may become "almost unbreakable."',
    timecode: 1815,
  },
];

export { easy, hard };
